config/routes.rb
Rails.application.routes.draw do
  resources :haberes
  resources :subcategoria
  resources :categoria

end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
	has_many :subcategorium
end

app/models/habere.rb
class Habere < ActiveRecord::Base
  belongs_to :subcategorium
end

app/models/subcategorium.rb
class Subcategorium < ActiveRecord::Base
  belongs_to :categorium
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  before_action :set_categorium, only: [:show, :edit, :update, :destroy]

  # GET /categoria
  # GET /categoria.json
  def index
    @categoria = Categorium.all
  end

  # GET /categoria/1
  # GET /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @categorium = Categorium.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria
  # POST /categoria.json
  def create
    @categorium = Categorium.new(categorium_params)

    respond_to do |format|
      if @categorium.save
        format.html { redirect_to @categorium, notice: 'Categorium was successfully created.' }
        format.json { render :show, status: :created, location: @categorium }
      else
        format.html { render :new }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1
  # PATCH/PUT /categoria/1.json
  def update
    respond_to do |format|
      if @categorium.update(categorium_params)
        format.html { redirect_to @categorium, notice: 'Categorium was successfully updated.' }
        format.json { render :show, status: :ok, location: @categorium }
      else
        format.html { render :edit }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1
  # DELETE /categoria/1.json
  def destroy
    @categorium.destroy
    respond_to do |format|
      format.html { redirect_to categoria_url, notice: 'Categorium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorium
      @categorium = Categorium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categorium_params
      params.require(:categorium).permit(:categoria)
    end
end

app/controllers/haberes_controller.rb
class HaberesController < ApplicationController
  before_action :set_habere, only: [:show, :edit, :update, :destroy]

  # GET /haberes
  # GET /haberes.json
  def index
    @haberes = Habere.all
  end

  # GET /haberes/1
  # GET /haberes/1.json
  def show
  end

  # GET /haberes/new
  def new
    @habere = Habere.new
  end

  # GET /haberes/1/edit
  def edit
  end

  # POST /haberes
  # POST /haberes.json
  def create
    @habere = Habere.new(habere_params)

    respond_to do |format|
      if @habere.save
        format.html { redirect_to @habere, notice: 'Habere was successfully created.' }
        format.json { render :show, status: :created, location: @habere }
      else
        format.html { render :new }
        format.json { render json: @habere.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /haberes/1
  # PATCH/PUT /haberes/1.json
  def update
    respond_to do |format|
      if @habere.update(habere_params)
        format.html { redirect_to @habere, notice: 'Habere was successfully updated.' }
        format.json { render :show, status: :ok, location: @habere }
      else
        format.html { render :edit }
        format.json { render json: @habere.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /haberes/1
  # DELETE /haberes/1.json
  def destroy
    @habere.destroy
    respond_to do |format|
      format.html { redirect_to haberes_url, notice: 'Habere was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habere
      @habere = Habere.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def habere_params
      params.require(:habere).permit(:sueldo_base, :subcategorium_id)
    end
end

app/controllers/subcategoria_controller.rb
class SubcategoriaController < ApplicationController
  before_action :set_subcategorium, only: [:show, :edit, :update, :destroy]

  # GET /subcategoria
  # GET /subcategoria.json
  def index
    @subcategoria = Subcategorium.all
  end

  # GET /subcategoria/1
  # GET /subcategoria/1.json
  def show
  end

  # GET /subcategoria/new
  def new
    @subcategorium = Subcategorium.new
  end

  # GET /subcategoria/1/edit
  def edit
  end

  # POST /subcategoria
  # POST /subcategoria.json
  def create
    @subcategorium = Subcategorium.new(subcategorium_params)

    respond_to do |format|
      if @subcategorium.save
        format.html { redirect_to @subcategorium, notice: 'Subcategorium was successfully created.' }
        format.json { render :show, status: :created, location: @subcategorium }
      else
        format.html { render :new }
        format.json { render json: @subcategorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategoria/1
  # PATCH/PUT /subcategoria/1.json
  def update
    respond_to do |format|
      if @subcategorium.update(subcategorium_params)
        format.html { redirect_to @subcategorium, notice: 'Subcategorium was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcategorium }
      else
        format.html { render :edit }
        format.json { render json: @subcategorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategoria/1
  # DELETE /subcategoria/1.json
  def destroy
    @subcategorium.destroy
    respond_to do |format|
      format.html { redirect_to subcategoria_url, notice: 'Subcategorium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategorium
      @subcategorium = Subcategorium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcategorium_params
      params.require(:subcategorium).permit(:subcategoria, :categorium_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/haberes_helper.rb
module HaberesHelper
end

app/helpers/subcategoria_helper.rb
module SubcategoriaHelper
end

app/views/categoria/_form.html.erb
<%= form_for(@categorium) do |f| %>
  <% if @categorium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categorium.errors.count, "error") %> prohibited this categorium from being saved:</h2>

      <ul>
      <% @categorium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :categoria %><br>
    <%= f.text_field :categoria %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categoria/edit.html.erb
<h1>Editing Categorium</h1>

<%= render 'form' %>

<%= link_to 'Show', @categorium %> |
<%= link_to 'Back', categoria_path %>

app/views/categoria/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categoria</h1>

<table>
  <thead>
    <tr>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categoria.each do |categorium| %>
      <tr>
        <td><%= categorium.categoria %></td>
        <td><%= link_to 'Show', categorium %></td>
        <td><%= link_to 'Edit', edit_categorium_path(categorium) %></td>
        <td><%= link_to 'Destroy', categorium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categorium', new_categorium_path %>

app/views/categoria/new.html.erb
<h1>New Categorium</h1>

<%= render 'form' %>

<%= link_to 'Back', categoria_path %>

app/views/categoria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Categoria:</strong>
  <%= @categorium.categoria %>
</p>

<%= link_to 'Edit', edit_categorium_path(@categorium) %> |
<%= link_to 'Back', categoria_path %>

app/views/haberes/_form.html.erb
<%= form_for(@habere) do |f| %>
  
  <div class="field">
    <%= f.label :categorium_id %><br>
    <%= collection_select(nil, :categorium_id, Categorium.order(:categoria), :id, :categoria, include_blank: :true) %>
  </div>
  <div class="field">
    <%= f.label :subcategorium_id %><br>
    <%= grouped_collection_select(:habere, :subcategorium_id, Categorium.order(:categoria), :subcategorium, :categoria, :id, :subcategoria, include_blank: :true) %>
  </div>
  <div class="field">
    <%= f.label :sueldo_base %><br>
    <%= f.number_field :sueldo_base %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/haberes/edit.html.erb
<h1>Editing Habere</h1>

<%= render 'form' %>

<%= link_to 'Show', @habere %> |
<%= link_to 'Back', haberes_path %>

app/views/haberes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Haberes</h1>

<table>
  <thead>
    <tr>
      <th>Sueldo base</th>
      <th>Subcategorium</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @haberes.each do |habere| %>
      <tr>
        <td><%= habere.sueldo_base %></td>
        <td><%= habere.subcategorium.subcategoria %></td>
        <td><%= link_to 'Show', habere %></td>
        <td><%= link_to 'Edit', edit_habere_path(habere) %></td>
        <td><%= link_to 'Destroy', habere, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Habere', new_habere_path %>

app/views/haberes/new.html.erb
<h1>New Habere</h1>

<%= render 'form' %>

<%= link_to 'Back', haberes_path %>

app/views/haberes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sueldo base:</strong>
  <%= @habere.sueldo_base %>
</p>

<p>
  <strong>Subcategorium:</strong>
  <%= @habere.subcategorium.subcategoria %>
</p>

<%= link_to 'Edit', edit_habere_path(@habere) %> |
<%= link_to 'Back', haberes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Relacion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/subcategoria/_form.html.erb
<%= form_for(@subcategorium) do |f| %>
  <% if @subcategorium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategorium.errors.count, "error") %> prohibited this subcategorium from being saved:</h2>

      <ul>
      <% @subcategorium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subcategoria %><br>
    <%= f.text_field :subcategoria %>
  </div>
  <div class="field">
    <%= f.label :categorium_id %><br>
    <%= collection_select(:subcategorium, :categorium_id, Categorium.all, :id, :categoria) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcategoria/edit.html.erb
<h1>Editing Subcategorium</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategorium %> |
<%= link_to 'Back', subcategoria_path %>

app/views/subcategoria/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subcategoria</h1>

<table>
  <thead>
    <tr>
      <th>Subcategoria</th>
      <th>Categorium</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcategoria.each do |subcategorium| %>
      <tr>
        <td><%= subcategorium.subcategoria %></td>
        <td><%= subcategorium.categorium.categoria %></td>
        <td><%= link_to 'Show', subcategorium %></td>
        <td><%= link_to 'Edit', edit_subcategorium_path(subcategorium) %></td>
        <td><%= link_to 'Destroy', subcategorium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategorium', new_subcategorium_path %>

app/views/subcategoria/new.html.erb
<h1>New Subcategorium</h1>

<%= render 'form' %>

<%= link_to 'Back', subcategoria_path %>

app/views/subcategoria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subcategoria:</strong>
  <%= @subcategorium.subcategoria %>
</p>

<p>
  <strong>Categorium:</strong>
  <%= @subcategorium.categorium.categoria %>
</p>

<%= link_to 'Edit', edit_subcategorium_path(@subcategorium) %> |
<%= link_to 'Back', subcategoria_path %>